export const UPDATE_PURCHASE_STATE = "UPDATE_PURCHASE_STATE";
export const ADD_INGREDIANT_HANDLER = "ADD_INGREDIANT_HANDLER";
export const REMOVE_INGREDIANT_HANDLER = "REMOVE_INGREDIANT_HANDLER";
export const INIT_ORDERS = "INIT_ORDERS";
export const ADD_ORDER = "ADD_ORDER";